name: Deploy Swagger UI

on:
  push:
    branches:
      - main # Trigger the workflow when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Fetch available tags
      - name: Fetch available tags
        id: get-tags
        run: |
          # Fetch all tags and format as JSON array
          git fetch --tags
          TAGS=$(git tag --sort=-version:refname | head -20 | grep -v '^$' | jq -R . | jq -s -c .)
          if [ "$TAGS" = "[]" ] || [ -z "$TAGS" ]; then
            TAGS="[]"
          fi
          echo "tags=$TAGS" >> $GITHUB_OUTPUT
          echo "Available tags: $TAGS"

      # Step 3: Move YAML files to swagger-ui directory
      - name: Move YAML files
        run: |
          # Check the files in the openapi/modules directory
          find openapi/modules -name '*.yaml'
          # Copy YAML files to the /swagger-ui directory
          find openapi/modules -name '*.yaml' -exec cp {} swagger-ui/ \;

      # Step 4: Run the Node.js script to generate swagger-ui-initializer.js
      - name: Generate Swagger UI initializer
        env:
          AVAILABLE_TAGS: ${{ steps.get-tags.outputs.tags }}
        run: |
          echo "AVAILABLE_TAGS environment variable: $AVAILABLE_TAGS"
          node generate-swagger-initializer.js

      # Step 5: Deploy Swagger UI and OpenAPI files to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./swagger-ui # The directory with Swagger UI static files
